### ISSUE TITLE
The Mac OS binary needs execute permissions set in order to run

### ISSUE THREAD

**Issue by alzadude** [digital-dj-tools/dj-data-converter#12]
When downloaded, the Mac OS binary won't have execute permissions set, and as such it won't be runnable unless a) the user spots that the reason is due to incorrect file permissions, and b) knows how to correct them.

Providing an installer or installation script is out of scope for the time being, so perhaps a tar archive of the binary could be provided, where execute permissions have already been set and should be preserved when the archive is extracted.

**Comment by alzadude** [comment]
Tar archive for Mac OS binary: [dj-data-converter-macos.tar.gz](https://github.com/digital-dj-tools/dj-data-converter/files/3328057/dj-data-converter-macos.tar.gz)

**Comment by paveyn** [comment]
@alzadude Thanks for doing the above! Works like magic. Great job on building this library. Its very helpful.
1 small issue, I realized it didn't export all of my traktor tracks into rekordbox.xml(199 out 235). Maybe i missed a setting or something. Just wanted to throw it out there so you aware of it.
Otherwise great job man

**Comment by alzadude** [comment]
> @alzadude Thanks for doing the above! Works like magic. Great job on building this library. Its very helpful.

No worries, thanks for testing it out! Since you've confirmed it's working, I'll release a new version with these changes 🙂

Btw: if you find that your Traktor playlists didn't get converted, and you want that feature, this is not available in the basic edition, it's only available in the pro edition (see the feature comparison [here](https://github.com/digital-dj-tools/dj-data-converter#features)). If that's of interest, please email me for pricing 🙂 

Thanks!

**Comment by paveyn** [comment]
Haha sure,
I don't really need the feature, but would love to chip in something
regardless. Just let me know how I can do that.

Thanks for the work you doing man :).
