### ISSUE TITLE
I don't know what to do after open prompt

### ISSUE THREAD

**Issue by bshlight** [digital-dj-tools/dj-data-converter#17]
Hi, first of all thanks to you for made this tool and share
I read usage but don't get how to use this
What I can do is open prompt
please help

![image](https://user-images.githubusercontent.com/55081823/64514621-f6d64900-d325-11e9-8c1b-4a49d12a1bb2.png)

**Comment by alzadude** [comment]
Hi @bshlight,

Sorry you're struggling with the command line interface!

It looks like you've downloaded the app to `C:\Users\danni\Desktop\dj-data-converter-win`.

If that's correct, then the following sequence of commands should work at the prompt:
```
cd C:\Users\danni\Desktop\dj-data-converter-win
dj-data-converter-win.exe C:\Users\danni\Documents\Native Instruments\Traktor 3.2.0\collection.nml"
```
That should convert your Traktor collection and create a `rekordbox.xml` file in the same directory.

Try it and let me know! 🙂

**Comment by bshlight** [comment]
![image](https://user-images.githubusercontent.com/55081823/64618186-be646700-d41a-11e9-98c2-92cd40c904cd.png)

Thank you for answering but I still can't make it
after I type `cd C:\Users\danni\Desktop\dj-data-converter-win` app still close so fast 
and xml file not appear
