### ISSUE TITLE
Fix for error when converting nml from Traktor 3.4.0

### ISSUE THREAD

**Issue by Xense92** [digital-dj-tools/dj-data-converter#42]
The conversion tool would error out on converting NML files from Traktor 3.4.0

Upon inspection of the NML file, it noticed that an extra tag was added with respect to the previous Traktor NML exports

The last part of the file now looks like:
`</NODE>`
`</PLAYLISTS>`
`<INDEXING></INDEXING>`
`</NML>`

I got it to work again by removing the 'indexing' tags an obtain a file ending like:

`</NODE>`
`</PLAYLISTS>`
`</NML>`

After doing this small change, I've been able to import the xml into rekordbox again :)!

This could be fixed by updating the parser I suppose. But for now this is an easy workaround.

**Comment by tommyhobbs** [comment]
I wrote a quick `.bat` script to help me convert Traktor to Rekordbox on Windows and automate @Xense92's solution. 

```ECHO Started convertion of $COLLECTION.nml to Rekordbox

@echo off
    setlocal enableextensions disabledelayedexpansion

    set "print=1"
    (
        for /f "usebackq delims=" %%a in ("./$COLLECTION.nml"
        ) do for /f "tokens=1 delims=/<> " %%b in ("%%a"
        ) do if /i "%%~b"=="INDEXING" (
            if defined print (set "print=") else (set "print=1")        
        ) else if defined print echo(%%a
    ) > "./$COLLECTION-to-convert.nml"


%~dp0dj-data-converter.exe "./$COLLECTION-to-convert.nml"
PAUSE
```

**Comment by alzadude** [comment]
Hi @Xense92 @tommyhobbs I've got a candidate fix, please can you try out this build and let me know if it resolves the issue on your collections? Thanks 🙏🙂

Mac: https://github.com/digital-dj-tools/dj-data-converter/suites/3693863242/artifacts/90076864

Windows: https://github.com/digital-dj-tools/dj-data-converter/suites/3693863242/artifacts/90076866

**Comment by alzadude** [comment]
Hi again @Xense92 @tommyhobbs it's been confirmed separately by another user that this fix resolves the issue, so I'll go ahead and merge it and then release a new version.

Thanks 🙏🙂
